name: Unit tests

on:
  workflow_run:
    workflows: ["Lint code"]
    types:
      - completed

jobs:
    django_tests:
        name: Run Django tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11
            - run: cd backend/playfit
            - run: pip install -r requirements.txt
            - run: python manage.py test

    flutter_tests:
        name: Run Flutter tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.19.0
            - run: flutter pub get
            - run: flutter test
